### ISSUE TITLE
Compatibility Debian 10 + stdlib >5.0

### ISSUE THREAD

**Issue by Miminoux** [MetaCenterCloudPuppet/cesnet-kerberos#2]
Hi,
Have you checked for compatibility with debian 10 and stdlib >5.0 ?
I briefely read your module and to me it should be compatible with those versions.
Maybe you can also check for other OS versions.
Thanks

**Comment by valtri** [comment]
Hello, yes, it looks like everything works OK. Updated in 1.1.2.
